name: "CodeBeaver OSS Testing"
description: "Run AI-powered unit tests and E2E tests for your codebase"
author: "CodeBeaver Team"
branding:
  icon: "check-circle"
  color: "blue"

inputs:
  action-type:
    description: "Type of tests to run (unit, e2e, or both)"
    required: false
    default: "both"
  file-path:
    description: "Path to the file to analyze for unit tests"
    required: false
  config-file:
    description: "Path to the YAML configuration file"
    required: false
    default: "codebeaver.yml"
  template:
    description: "Testing framework template to use (e.g., pytest, jest, vitest)"
    required: false
  max-files-to-test:
    description: "Maximum number of files to generate unit tests for"
    required: false
    default: "10"
  verbose:
    description: "Enable verbose logging output"
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
        cache: "pip"

    - name: Install Chrome
      shell: bash
      run: |
        if [ "$(uname)" == "Linux" ]; then
          wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
          echo "CHROME_PATH=/usr/bin/google-chrome" >> $GITHUB_ENV
        elif [ "$(uname)" == "Darwin" ]; then
          echo "CHROME_PATH=/Applications/Google Chrome.app/Contents/MacOS/Google Chrome" >> $GITHUB_ENV
        else
          echo "Unsupported operating system"
          exit 1
        fi

    - name: Install CodeBeaver
      shell: bash
      run: |
        pip install codebeaver

    - name: Run CodeBeaver - Both Tests
      if: inputs.action-type == 'both'
      shell: bash
      run: |
        VERBOSE_FLAG=""
        if [ "${{ inputs.verbose }}" == "true" ]; then
          VERBOSE_FLAG="--verbose"
        fi

        codebeaver $VERBOSE_FLAG
      env:
        OPENAI_API_KEY: ${{ env.OPENAI_API_KEY }}
        CHROME_INSTANCE_PATH: ${{ env.CHROME_PATH }}
        STARTING_URL: ${{ env.STARTING_URL }}
        GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ env.GITHUB_TOKEN }}
        commit-message: "test: Update tests with CodeBeaver"
        title: "🤖 CodeBeaver: Update Tests"
        body: |
          This PR was automatically created by CodeBeaver to update tests.

          ### Changes include:
          - Generated/updated unit tests

          Please review the changes and merge if everything looks good.
        branch: codebeaver/update-tests
        base: ${{ github.head_ref || github.ref_name }}
        labels: |
          automated-pr
          tests

    - name: Run CodeBeaver - Unit Tests
      if: inputs.action-type == 'unit'
      shell: bash
      run: |
        VERBOSE_FLAG=""
        if [ "${{ inputs.verbose }}" == "true" ]; then
          VERBOSE_FLAG="--verbose"
        fi

        CONFIG_OPTION=""
        if [ -n "${{ inputs.config-file }}" ]; then
          CONFIG_OPTION="--config ${{ inputs.config-file }}"
        fi
        MAX_FILES_OPTION=""
        if [ -n "${{ inputs.max-files-to-test }}" ]; then
          MAX_FILES_OPTION="--max-files-to-test ${{ inputs.max-files-to-test }}"
        fi
        FILE_OPTION=""
        if [ -n "${{ inputs.file-path }}" ]; then
          FILE_OPTION="--file ${{ inputs.file-path }}"
        fi

        codebeaver unit $VERBOSE_FLAG $CONFIG_OPTION $FILE_OPTION $MAX_FILES_OPTION
      env:
        OPENAI_API_KEY: ${{ env.OPENAI_API_KEY }}
        CHROME_INSTANCE_PATH: ${{ env.CHROME_PATH }}
        GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ env.GITHUB_TOKEN }}
        commit-message: "test: Update tests with CodeBeaver"
        title: "🤖 CodeBeaver: Update Tests"
        body: |
          This PR was automatically created by CodeBeaver to update tests.

          ### Changes include:
          - Generated/updated unit tests

          Please review the changes and merge if everything looks good.
        branch: codebeaver/update-tests
        base: ${{ github.head_ref || github.ref_name }}
        labels: |
          automated-pr
          tests

    - name: Run CodeBeaver - E2E Tests
      if: inputs.action-type == 'e2e'
      shell: bash
      run: |
        VERBOSE_FLAG=""
        if [ "${{ inputs.verbose }}" == "true" ]; then
          VERBOSE_FLAG="--verbose"
        fi

        CONFIG_OPTION=""
        if [ -n "${{ inputs.config-file }}" ]; then
          CONFIG_OPTION="--config ${{ inputs.config-file }}"
        fi

        codebeaver e2e $VERBOSE_FLAG $CONFIG_OPTION
      env:
        OPENAI_API_KEY: ${{ env.OPENAI_API_KEY }}
        CHROME_INSTANCE_PATH: ${{ env.CHROME_PATH }}
        STARTING_URL: ${{ env.STARTING_URL }}
        GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
