name: CodeBeaver CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch: # Allow manual triggering

jobs:
  unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run CodeBeaver Unit Tests
        uses: codebeaver-ai/codebeaver-action@v1
        with:
          action-type: "unit"
          verbose: "true"
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

  e2e-tests:
    name: Run E2E Tests
    runs-on: ubuntu-latest
    # Optional: Add conditions on when to run E2E tests
    # if: github.event_name == 'workflow_dispatch'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run CodeBeaver E2E Tests
        uses: codebeaver-ai/codebeaver-action@v1
        with:
          action-type: "e2e"
          config-file: "codebeaver.yml"
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          # Optional: Override the starting URL from codebeaver.yml
          # STARTING_URL: "https://staging.example.com"
